struct Task:
    id: Int
    title: String
    completed: Bool

def create_task(id: Int, title: String) -> Task:
    mut t := Task()
    t.id = id
    t.title = title
    t.completed = false
    return t

def show_task(t: Task):
    print_str("--- Task Detail ---")
    print_str("ID:")
    print(t.id)
    print_str("Title:")
    print_str(t.title)
    print_str("Status:")
    if t.completed:
        print_str("Completed")
    else:
        print_str("Pending")
    print_str("-------------------")
