def test_while_break() -> Void:
    mut i := 0
    while i < 10:
        if i == 5:
            break
        i = i + 1
    lpp_print_int(i) # expect 5

def test_while_continue() -> Void:
    mut sum := 0
    mut i := 0
    while i < 10:
        i = i + 1
        if i % 2 == 0:
            continue
        sum = sum + i
    lpp_print_int(sum) # expect 1 + 3 + 5 + 7 + 9 = 25

def test_for_range_break_continue() -> Void:
    mut sum := 0
    for i in range(0, 10):
        if i == 7:
            break
        if i % 2 == 0:
            continue
        sum = sum + i
    lpp_print_int(sum) # expect 1 + 3 + 5 = 9

def test_for_in_list_break_continue() -> Void:
    numbers := [10, 15, 20, 25, 30, 35, 40]
    mut sum := 0
    for num in numbers:
        if num == 35:
            break
        if num % 20 == 0:
            continue
        sum = sum + num
    lpp_print_int(sum) # 10 + 15 + 25 + 30 = 80

def main():
    test_while_break()
    test_while_continue()
    test_for_range_break_continue()
    test_for_in_list_break_continue()
