use std::fmt::Write as _;

use crate::{AbiRegistry, AbiType, SchemaError};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedAbi {
    pub rust: String,
    pub c_header: String,
    pub symbols: String,
    pub markdown: String,
}

pub fn generate(registry: &AbiRegistry) -> Result<GeneratedAbi, SchemaError> {
    registry.validate()?;
    Ok(GeneratedAbi {
        rust: render_rust(registry),
        c_header: render_c_header(registry),
        symbols: render_symbols(registry),
        markdown: render_markdown(registry),
    })
}

fn render_rust(registry: &AbiRegistry) -> String {
    let mut header = String::new();
    header.push_str("// @generated by lpp-abi-gen; do not edit by hand.\n");
    header.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    header.push_str("pub enum AbiType { Bool, F64, I32, I64, Void }\n");
    header.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    header.push_str(
        "pub enum SemanticAbiType { Any, Bool, F64, I32, I64, Str, StrSlice, VectorI64x2, Void }\n",
    );
    header.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    header.push_str("pub struct BuiltinAbi {\n");
    header.push_str("    pub name: &'static str,\n");
    header.push_str("    pub symbol: &'static str,\n");
    header.push_str("    pub parameters: &'static [AbiType],\n");
    header.push_str("    pub result: AbiType,\n");
    header.push_str("    pub semantic_parameters: &'static [SemanticAbiType],\n");
    header.push_str("    pub semantic_result: SemanticAbiType,\n");
    header.push_str("}\n");
    header.push('\n');
    let mut output = header;
    let _ = writeln!(
        output,
        "pub const LPP_ABI_VERSION: u32 = {};",
        registry.abi_version
    );
    output.push_str("pub static BUILTINS: &[BuiltinAbi] = &[");
    for builtin in &registry.builtins {
        let parameters = builtin
            .lowering_parameters
            .iter()
            .map(|kind| format!("AbiType::{}", rust_type_variant(*kind)))
            .collect::<Vec<_>>()
            .join(", ");
        let semantic_parameters = builtin
            .parameters
            .iter()
            .map(|kind| format!("SemanticAbiType::{}", semantic_type_variant(*kind)))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            output,
            "    BuiltinAbi {{ name: {:?}, symbol: {:?}, parameters: &[{}], result: AbiType::{}, semantic_parameters: &[{}], semantic_result: SemanticAbiType::{} }},",
            builtin.name,
            builtin.symbol,
            parameters,
            rust_type_variant(builtin.lowering_result),
            semantic_parameters,
            semantic_type_variant(builtin.semantic_result_type())
        );
    }
    output.push_str("];");
    output
}

fn render_c_header(registry: &AbiRegistry) -> String {
    let mut output = String::from(
        "/* @generated by lpp-abi-gen; do not edit by hand. */\n\
         #ifndef LPP_ABI_H\n\
         #define LPP_ABI_H\n\
         \n\
         #include <stdint.h>\n\
         \n\
         #ifdef __cplusplus\n\
         extern \"C\" {\n\
         #endif\n\
         \n",
    );
    let _ = writeln!(output, "#define LPP_ABI_VERSION {}", registry.abi_version);
    output.push('\n');
    for (symbol, signature) in registry.canonical_signatures() {
        if !symbol.starts_with("lpp_") {
            continue;
        }
        let parameters = if signature.parameters.is_empty() {
            "void".to_string()
        } else {
            signature
                .parameters
                .iter()
                .map(|kind| kind.c_type())
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            output,
            "{} {}({});",
            signature.result.c_type(),
            symbol,
            parameters
        );
    }
    output.push_str(
        "\n#ifdef __cplusplus\n\
         }\n\
         #endif\n\
         \n\
         #endif /* LPP_ABI_H */\n",
    );
    output
}

fn render_symbols(registry: &AbiRegistry) -> String {
    let mut output = String::new();
    for symbol in registry.symbols() {
        let _ = writeln!(output, "{symbol}");
    }
    output
}

fn render_markdown(registry: &AbiRegistry) -> String {
    let mut output = String::from(
        "# Generated L++ builtin ABI reference\n\
         \n\
         This file is generated from `abi/builtins.toml`. Do not edit it by hand.\n\
         \n\
         | Source name | Runtime symbol | Feature | Lowered signature | Targets |\n\
         |---|---|---|---|---|\n",
    );
    for builtin in &registry.builtins {
        let parameters = builtin
            .lowering_parameters
            .iter()
            .map(|kind| rust_type_name(*kind))
            .collect::<Vec<_>>()
            .join(", ");
        let targets = builtin
            .targets
            .iter()
            .map(|target| format!("{target:?}").to_lowercase())
            .collect::<Vec<_>>()
            .join(", ");
        let symbol = if builtin.symbol.is_empty() {
            "\u{2014}"
        } else {
            builtin.symbol.as_str()
        };
        let _ = writeln!(
            output,
            "| `{}` | `{}` | `{}` | `({}) -> {}` | {} |",
            builtin.name,
            symbol,
            builtin.feature,
            parameters,
            rust_type_name(builtin.lowering_result),
            targets
        );
    }
    output
}

const fn rust_type_variant(kind: AbiType) -> &'static str {
    match kind {
        AbiType::Any | AbiType::Str | AbiType::StrSlice | AbiType::VectorI64x2 => "I64",
        AbiType::Bool => "Bool",
        AbiType::F64 => "F64",
        AbiType::I32 => "I32",
        AbiType::I64 => "I64",
        AbiType::Void => "Void",
    }
}

const fn semantic_type_variant(kind: AbiType) -> &'static str {
    match kind {
        AbiType::Any => "Any",
        AbiType::Bool => "Bool",
        AbiType::F64 => "F64",
        AbiType::I32 => "I32",
        AbiType::I64 => "I64",
        AbiType::Str => "Str",
        AbiType::StrSlice => "StrSlice",
        AbiType::VectorI64x2 => "VectorI64x2",
        AbiType::Void => "Void",
    }
}

const fn rust_type_name(kind: AbiType) -> &'static str {
    match kind {
        AbiType::Any => "any",
        AbiType::Bool => "bool",
        AbiType::F64 => "f64",
        AbiType::I32 => "i32",
        AbiType::I64 => "i64",
        AbiType::Str => "str",
        AbiType::StrSlice => "str_slice",
        AbiType::VectorI64x2 => "vector_i64x2",
        AbiType::Void => "void",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::v1_registry;

    #[test]
    fn output_is_deterministic() {
        let registry = v1_registry().unwrap();
        assert_eq!(generate(&registry).unwrap(), generate(&registry).unwrap());
    }

    #[test]
    fn generated_header_has_one_declaration_per_runtime_symbol() {
        let registry = v1_registry().unwrap();
        let generated = generate(&registry).unwrap();
        let declaration_count = generated
            .c_header
            .lines()
            .filter(|line| line.contains(" lpp_") && line.ends_with(");"))
            .count();
        assert_eq!(declaration_count, registry.runtime_symbols().len());
    }

    #[test]
    fn generated_rust_carries_semantic_signatures() {
        let registry = v1_registry().unwrap();
        let generated = generate(&registry).unwrap();
        assert!(generated.rust.contains("pub enum SemanticAbiType"));
        let print_str = generated
            .rust
            .lines()
            .find(|line| line.contains("name: \"print_str\""))
            .expect("the registry contains print_str");
        assert!(print_str.contains("semantic_parameters: &[SemanticAbiType::Str]"));
        assert!(print_str.contains("semantic_result: SemanticAbiType::Void"));
    }
}
