#!/usr/bin/env python3
"""SamarOS font atlas generator.

Renders anti-aliased 8-bit coverage bitmaps for a handful of UI faces and
emits them as a freestanding C table the kernel can blend directly.  The
kernel has no font rasteriser (and no libc), so all glyph work happens here
at build time.

    usage: genfont.py <inter-variable.ttf> <mono.ttf> <out.c> <out.h>
"""
import sys
from PIL import Image, ImageDraw, ImageFont

ASCII = "".join(chr(c) for c in range(32, 127))
DIGITS = "0123456789: APM"

# id, family, px size, variable-weight (None for static), charset
FACES = [
    ("SMALL",     "ui",   11, 500, ASCII),   # 0  captions / secondary text
    ("BODY",      "ui",   13, 400, ASCII),   # 1  body copy
    ("BODY_SEMI", "ui",   13, 600, ASCII),   # 2  emphasised body
    ("TITLE",     "ui",   15, 600, ASCII),   # 3  window + section titles
    ("DISPLAY",   "ui",   34, 250, DIGITS),  # 4  lock screen clock
    ("MONO",      "mono", 12, None, ASCII),  # 5  terminal
    ("CAPS",      "ui",   10, 700, ASCII),   # 6  uppercase micro labels
    ("HEAD",      "ui",   20, 600, ASCII),   # 7  app headlines
]


def load(family, path_ui, path_mono, size, weight):
    path = path_ui if family == "ui" else path_mono
    f = ImageFont.truetype(path, size)
    if weight is not None:
        try:
            f.set_variation_by_axes([weight])
        except Exception:
            pass
    return f


def render(font, ch):
    """Return (w, h, bearing_x, bearing_y, advance, coverage bytes)."""
    pad = 4
    box = font.getbbox(ch)
    adv = int(round(font.getlength(ch)))
    if box is None or ch == " ":
        return 0, 0, 0, 0, max(adv, 1), b""
    w = box[2] - box[0]
    h = box[3] - box[1]
    if w <= 0 or h <= 0:
        return 0, 0, 0, 0, max(adv, 1), b""
    img = Image.new("L", (w + pad * 2, h + pad * 2), 0)
    d = ImageDraw.Draw(img)
    d.text((pad - box[0], pad - box[1]), ch, font=font, fill=255)
    bbox = img.getbbox()
    if bbox is None:
        return 0, 0, 0, 0, max(adv, 1), b""
    img = img.crop(bbox)
    bx = bbox[0] - pad
    by = bbox[1] - pad + box[1]
    return img.width, img.height, bx, by, max(adv, 1), img.tobytes()


def main():
    ui_path, mono_path, out_c, out_h = sys.argv[1:5]
    chunks, tables, total = [], [], 0

    for idx, (name, family, size, weight, charset) in enumerate(FACES):
        font = load(family, ui_path, mono_path, size, weight)
        ascent, descent = font.getmetrics()
        blob = bytearray()
        glyphs = []
        index = [-1] * 96
        for ch in charset:
            code = ord(ch)
            if not (32 <= code < 127):
                continue
            w, h, bx, by, adv, data = render(font, ch)
            index[code - 32] = len(glyphs)
            glyphs.append((len(blob), w, h, bx, by, adv))
            blob += data
        total += len(blob)

        rows = ", ".join(str(b) for b in blob) if blob else "0"
        chunks.append(
            "static const unsigned char f%d_bits[] = { %s };\n" % (idx, rows)
        )
        chunks.append("static const sm_glyph f%d_glyphs[] = {\n" % idx)
        for off, w, h, bx, by, adv in glyphs:
            chunks.append("  {%d,%d,%d,%d,%d,%d},\n" % (off, w, h, bx, by, adv))
        chunks.append("};\n")
        chunks.append(
            "static const short f%d_index[96] = { %s };\n"
            % (idx, ", ".join(str(i) for i in index))
        )
        tables.append(
            "  { f%d_glyphs, f%d_bits, f%d_index, %d, %d, %d },"
            % (idx, idx, idx, ascent + descent + 2, ascent, size)
        )

    with open(out_h, "w") as fh:
        fh.write(
            "/* generated by tools/genfont.py — do not edit */\n"
            "#ifndef SAMAR_FONT_H\n#define SAMAR_FONT_H\n\n"
            "typedef struct { short off; unsigned char w, h;"
            " signed char bx, by; unsigned char adv; } sm_glyph;\n\n"
            "typedef struct {\n"
            "  const sm_glyph *glyphs;\n"
            "  const unsigned char *bits;\n"
            "  const short *index;\n"
            "  short line_height;\n"
            "  short ascent;\n"
            "  short px;\n"
            "} sm_face;\n\n"
            "extern const sm_face sm_faces[];\n"
            "extern const int sm_face_count;\n\n"
        )
        for i, (name, *_rest) in enumerate(FACES):
            fh.write("#define FONT_%s %d\n" % (name, i))
        fh.write("\n#endif\n")

    with open(out_c, "w") as fc:
        fc.write("/* generated by tools/genfont.py — do not edit */\n")
        fc.write('#include "font.h"\n\n')
        fc.writelines(chunks)
        fc.write("\nconst sm_face sm_faces[] = {\n")
        fc.write("\n".join(tables))
        fc.write("\n};\n")
        fc.write("const int sm_face_count = %d;\n" % len(FACES))

    print("font atlas: %d faces, %.1f KiB of coverage data" % (len(FACES), total / 1024))


if __name__ == "__main__":
    main()
