use crate::types::TypeRef;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ParamType {
    Specific(TypeRef),
    Any,
}

#[derive(Debug, Clone)]
pub struct Builtin {
    pub name: &'static str,
    pub symbol: &'static str,
    pub params: &'static [ParamType],
    pub return_type: TypeRef,
    // Cranelift parameter type tags: 0 = I64, 1 = I8, 2 = I32, 3 = F64
    pub cl_params: &'static [u8],
    pub cl_return: Option<u8>,
}

pub fn get_builtins() -> &'static [Builtin] {
    static BUILTINS: &[Builtin] = &[
        // Borrowed slice surface syntax. Type checking and MIR lowering refine
        // the generic element/result types; these entries make the names
        // visible to semantic resolution and declare the runtime ABI.
        Builtin {
            name: "str_slice",
            symbol: "lpp_slice_init",
            params: &[ParamType::Any, ParamType::Any, ParamType::Any],
            return_type: TypeRef::StrSlice,
            cl_params: &[0, 0, 0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "slice",
            symbol: "lpp_slice_init",
            params: &[ParamType::Any, ParamType::Any, ParamType::Any],
            // Refined to Slice[T] by the type checker; avoid heap allocation in
            // this static descriptor.
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "slice_len",
            symbol: "lpp_slice_len",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "slice_get",
            symbol: "lpp_slice_get",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_slice_get_bool",
            symbol: "lpp_slice_get_bool",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Bool,
            cl_params: &[0, 0],
            cl_return: Some(1),
        },
        Builtin {
            name: "slice_to_str",
            symbol: "lpp_str_slice_to_str",
            params: &[ParamType::Any],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_slice_to_str",
            symbol: "lpp_str_slice_to_str",
            params: &[ParamType::Any],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // Internal aggregate/task runtime ABI.
        Builtin {
            name: "lpp_tuple_alloc",
            symbol: "lpp_tuple_alloc",
            params: &[ParamType::Any, ParamType::Any, ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_task_new",
            symbol: "lpp_task_new",
            params: &[ParamType::Any, ParamType::Any, ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_task_poll",
            symbol: "lpp_task_poll",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_task_await",
            symbol: "lpp_task_await",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_executor_run",
            symbol: "lpp_executor_run",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_task_destroy",
            symbol: "lpp_task_destroy",
            params: &[ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // Overloaded/generic frontend functions
        Builtin {
            name: "print",
            symbol: "",
            params: &[ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: None,
        },
        // Linkable runtime targets
        Builtin {
            name: "print_str",
            symbol: "lpp_print_str",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_print_str",
            symbol: "lpp_print_str",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_print_int",
            symbol: "lpp_print_int",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_print_float",
            symbol: "lpp_print_float",
            params: &[ParamType::Specific(TypeRef::Float)],
            return_type: TypeRef::Void,
            cl_params: &[3],
            cl_return: None,
        },
        Builtin {
            name: "lpp_print_bool",
            symbol: "lpp_print_bool",
            params: &[ParamType::Specific(TypeRef::Bool)],
            return_type: TypeRef::Void,
            cl_params: &[1],
            cl_return: None,
        },
        Builtin {
            name: "fmod",
            symbol: "fmod",
            params: &[
                ParamType::Specific(TypeRef::Float),
                ParamType::Specific(TypeRef::Float),
            ],
            return_type: TypeRef::Float,
            cl_params: &[3, 3],
            cl_return: Some(3),
        },
        Builtin {
            name: "input",
            symbol: "lpp_input",
            params: &[],
            return_type: TypeRef::Str,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_input",
            symbol: "lpp_input",
            params: &[],
            return_type: TypeRef::Str,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_free_str",
            symbol: "lpp_free_str",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_arc_retain",
            symbol: "lpp_arc_retain",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // Non-atomic ARC. Emitted in place of the atomic pair when the
        // whole-program analysis proves no thread is ever spawned.
        Builtin {
            name: "lpp_arc_retain_local",
            symbol: "lpp_arc_retain_local",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_arc_retain_local",
            symbol: "lpp_arc_retain_local",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_arc_release_local",
            symbol: "lpp_arc_release_local",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_arc_release",
            symbol: "lpp_arc_release",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // ARC-managed allocation used by AOT struct lowering. The pointer is
        // represented as I64 in the current 64-bit L++ runtime ABI.
        Builtin {
            name: "lpp_arc_alloc",
            symbol: "lpp_arc_alloc",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // AOT-only typed ARC allocation: size plus a generated destructor
        // function pointer, both represented as I64 in the current ABI.
        Builtin {
            name: "lpp_arc_alloc_with_destructor",
            symbol: "lpp_arc_alloc_with_destructor",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_arena_begin",
            symbol: "lpp_arena_begin",
            params: &[],
            return_type: TypeRef::Int,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_arena_release",
            symbol: "lpp_arena_release",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_arena_retain",
            symbol: "lpp_arena_retain",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_arena_alloc",
            symbol: "lpp_arena_alloc",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_arena_release_node",
            symbol: "lpp_arena_release_node",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_closure_destroy",
            symbol: "lpp_closure_destroy",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_alloc",
            symbol: "lpp_alloc",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_free",
            symbol: "lpp_free",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_thread_spawn",
            symbol: "lpp_thread_spawn",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        // Alias: `len` and `get` for ergonomic list access
        Builtin {
            name: "len",
            symbol: "lpp_list_len",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "get",
            symbol: "lpp_list_get",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "list_new",
            symbol: "lpp_list_new",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_new",
            symbol: "lpp_list_new",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_new_arc",
            symbol: "lpp_list_new_arc",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "list_push",
            symbol: "lpp_list_push",
            // TypeChecker derives the element type from the concrete List[T].
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_push",
            symbol: "lpp_list_push",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_push_arc",
            symbol: "lpp_list_push_arc",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_push_float",
            symbol: "lpp_list_push_float",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Float)],
            return_type: TypeRef::Void,
            cl_params: &[0, 3],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_push_bool",
            symbol: "lpp_list_push_bool",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Bool)],
            return_type: TypeRef::Void,
            cl_params: &[0, 1],
            cl_return: None,
        },
        Builtin {
            name: "list_set",
            symbol: "lpp_list_set",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int), ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_set",
            symbol: "lpp_list_set",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int), ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_set_bool",
            symbol: "lpp_list_set_bool",
            params: &[
                ParamType::Any,
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Bool),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 1],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_set_float",
            symbol: "lpp_list_set_float",
            params: &[
                ParamType::Any,
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Float),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 3],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_set_arc",
            symbol: "lpp_list_set_arc",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int), ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "list_get",
            symbol: "lpp_list_get",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_get",
            symbol: "lpp_list_get",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_get_arc",
            symbol: "lpp_list_get_arc",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_get_float",
            symbol: "lpp_list_get_float",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Float,
            cl_params: &[0, 0],
            cl_return: Some(3),
        },
        Builtin {
            name: "lpp_list_get_bool",
            symbol: "lpp_list_get_bool",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Bool,
            cl_params: &[0, 0],
            cl_return: Some(1),
        },
        Builtin {
            name: "list_len",
            symbol: "lpp_list_len",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_len",
            symbol: "lpp_list_len",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "list_free",
            symbol: "lpp_list_free",
            params: &[ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_free",
            symbol: "lpp_list_free",
            params: &[ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // ── Map Hash Table library ──────────────────────────────────────────
        Builtin {
            name: "map_new",
            symbol: "lpp_map_new",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_map_new",
            symbol: "lpp_map_new",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "map_new_arc",
            symbol: "lpp_map_new_arc",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_map_new_arc",
            symbol: "lpp_map_new_arc",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "map_put",
            symbol: "lpp_map_put",
            params: &[ParamType::Any, ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_map_put",
            symbol: "lpp_map_put",
            params: &[ParamType::Any, ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_map_put_float",
            symbol: "lpp_map_put_float",
            params: &[ParamType::Any, ParamType::Any, ParamType::Specific(TypeRef::Float)],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 3],
            cl_return: None,
        },
        Builtin {
            name: "lpp_map_put_str",
            symbol: "lpp_map_put_str",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Str), ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_map_put_str_float",
            symbol: "lpp_map_put_str_float",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Float)],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 3],
            cl_return: None,
        },
        Builtin {
            name: "lpp_map_get_str_float",
            symbol: "lpp_map_get_str_float",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Float,
            cl_params: &[0, 0],
            cl_return: Some(3),
        },
        Builtin {
            name: "map_get",
            symbol: "lpp_map_get",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_map_get",
            symbol: "lpp_map_get",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_map_get_float",
            symbol: "lpp_map_get_float",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Float,
            cl_params: &[0, 0],
            cl_return: Some(3),
        },
        Builtin {
            name: "lpp_map_get_str",
            symbol: "lpp_map_get_str",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_map_has_str",
            symbol: "lpp_map_has_str",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_map_remove_str",
            symbol: "lpp_map_remove_str",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "map_has",
            symbol: "lpp_map_has",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_map_has",
            symbol: "lpp_map_has",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "map_len",
            symbol: "lpp_map_len",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_map_len",
            symbol: "lpp_map_len",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "map_remove",
            symbol: "lpp_map_remove",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_map_remove",
            symbol: "lpp_map_remove",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        // Networking — Full Go-style API
        // Dial (TCP + DNS + deadline)
        Builtin {
            name: "net_dial",
            symbol: "lpp_net_dial",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_dial",
            symbol: "lpp_net_dial",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        // Dial UDP
        Builtin {
            name: "net_dial_udp",
            symbol: "lpp_net_dial_udp",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_dial_udp",
            symbol: "lpp_net_dial_udp",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        // Listen TCP
        Builtin {
            name: "net_listen",
            symbol: "lpp_net_listen",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_listen",
            symbol: "lpp_net_listen",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // Listen UDP
        Builtin {
            name: "net_listen_udp",
            symbol: "lpp_net_listen_udp",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_listen_udp",
            symbol: "lpp_net_listen_udp",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // Accept (with timeout)
        Builtin {
            name: "net_accept",
            symbol: "lpp_net_accept",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_accept",
            symbol: "lpp_net_accept",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "net_accept_timeout",
            symbol: "lpp_net_accept_timeout",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_accept_timeout",
            symbol: "lpp_net_accept_timeout",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // Send
        Builtin {
            name: "net_send",
            symbol: "lpp_net_send",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_send",
            symbol: "lpp_net_send",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // Send all
        Builtin {
            name: "net_send_all",
            symbol: "lpp_net_send_all",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_send_all",
            symbol: "lpp_net_send_all",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // Recv
        Builtin {
            name: "net_recv",
            symbol: "lpp_net_recv",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_recv",
            symbol: "lpp_net_recv",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // Recv UDP
        Builtin {
            name: "net_recv_udp",
            symbol: "lpp_net_recv_udp",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_recv_udp",
            symbol: "lpp_net_recv_udp",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // Close
        Builtin {
            name: "net_close",
            symbol: "lpp_net_close",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_net_close",
            symbol: "lpp_net_close",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // Deadlines
        Builtin {
            name: "net_set_deadline",
            symbol: "lpp_net_set_deadline",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_set_deadline",
            symbol: "lpp_net_set_deadline",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "net_set_timeout",
            symbol: "lpp_net_set_timeout",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_set_timeout",
            symbol: "lpp_net_set_timeout",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // Non-blocking & Polling builtins for async C100K event loops
        Builtin {
            name: "net_set_nonblocking",
            symbol: "lpp_net_set_nonblocking",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_set_nonblocking",
            symbol: "lpp_net_set_nonblocking",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "net_poll",
            symbol: "lpp_net_poll",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_poll",
            symbol: "lpp_net_poll",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // Keepalive
        Builtin {
            name: "net_set_keepalive",
            symbol: "lpp_net_set_keepalive",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_set_keepalive",
            symbol: "lpp_net_set_keepalive",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0, 0, 0],
            cl_return: Some(0),
        },
        // DNS
        Builtin {
            name: "net_resolve",
            symbol: "lpp_net_resolve",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_resolve",
            symbol: "lpp_net_resolve",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // HTTP
        Builtin {
            name: "http_get",
            symbol: "lpp_http_get",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_http_get",
            symbol: "lpp_http_get",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "http_post",
            symbol: "lpp_http_post",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_http_post",
            symbol: "lpp_http_post",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0, 0, 0],
            cl_return: Some(0),
        },
        // Legacy compat
        Builtin {
            name: "net_connect",
            symbol: "lpp_net_connect",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_connect",
            symbol: "lpp_net_connect",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // JSON parsing
        Builtin {
            name: "json_parse",
            symbol: "lpp_json_parse",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_parse",
            symbol: "lpp_json_parse",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_get_int",
            symbol: "lpp_json_get_int",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_get_int",
            symbol: "lpp_json_get_int",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_get_str",
            symbol: "lpp_json_get_str",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_get_str",
            symbol: "lpp_json_get_str",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_get_obj",
            symbol: "lpp_json_get_obj",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_get_obj",
            symbol: "lpp_json_get_obj",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_free",
            symbol: "lpp_json_free",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_json_free",
            symbol: "lpp_json_free",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // Utilities
        Builtin {
            name: "parse_int",
            symbol: "lpp_parse_int",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_parse_int",
            symbol: "lpp_parse_int",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // File I/O (Existing & New)
        Builtin {
            name: "read_file",
            symbol: "lpp_read_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_read_file",
            symbol: "lpp_read_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "write_file",
            symbol: "lpp_write_file",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_write_file",
            symbol: "lpp_write_file",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "append_file",
            symbol: "lpp_append_file",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_append_file",
            symbol: "lpp_append_file",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "delete_file",
            symbol: "lpp_delete_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_delete_file",
            symbol: "lpp_delete_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "file_exists",
            symbol: "lpp_file_exists",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0), // I8 tag for bool
        },
        Builtin {
            name: "lpp_file_exists",
            symbol: "lpp_file_exists",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "file_size",
            symbol: "lpp_file_size",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_file_size",
            symbol: "lpp_file_size",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "file_copy",
            symbol: "lpp_file_copy",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_file_copy",
            symbol: "lpp_file_copy",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "file_move",
            symbol: "lpp_file_move",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_file_move",
            symbol: "lpp_file_move",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // ── String library (runtime/lpp_str.c) ──────────────────────────────
        Builtin {
            name: "str_concat",
            symbol: "lpp_str_concat",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_concat",
            symbol: "lpp_str_concat",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_repeat",
            symbol: "lpp_str_repeat",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_repeat",
            symbol: "lpp_str_repeat",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // str_split / lpp_str_split: the real result type is List[Str]
        // (Doc.md), which this const table cannot spell — the declared Void
        // is refined to List[Str] by the special case in
        // analysis/typecheck.rs. The delimiter is an Int codepoint, matching
        // the native ABI (runtime/lpp_str.c: lpp_str_split(s, i64 delim)).
        Builtin {
            name: "str_split",
            symbol: "lpp_str_split",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_split",
            symbol: "lpp_str_split",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_find",
            symbol: "lpp_str_find",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_find",
            symbol: "lpp_str_find",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_replace",
            symbol: "lpp_str_replace",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_replace",
            symbol: "lpp_str_replace",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_substr",
            symbol: "lpp_str_substr",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_substr",
            symbol: "lpp_str_substr",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_trim",
            symbol: "lpp_str_trim",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_trim",
            symbol: "lpp_str_trim",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // ── Process execution (runtime/lpp_exec.c) ──────────────────────────
        Builtin {
            name: "command_exec",
            symbol: "lpp_command_exec",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_command_exec",
            symbol: "lpp_command_exec",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "command_output",
            symbol: "lpp_command_output",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_command_output",
            symbol: "lpp_command_output",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "env_get",
            symbol: "lpp_env_get",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_env_get",
            symbol: "lpp_env_get",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "env_set",
            symbol: "lpp_env_set",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_env_set",
            symbol: "lpp_env_set",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // ── Directory / filesystem (runtime/lpp_dir.c) ──────────────────────
        Builtin {
            name: "dir_create",
            symbol: "lpp_dir_create",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_dir_create",
            symbol: "lpp_dir_create",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "dir_list",
            symbol: "lpp_dir_list",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_dir_list",
            symbol: "lpp_dir_list",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "dir_remove",
            symbol: "lpp_dir_remove",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_dir_remove",
            symbol: "lpp_dir_remove",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "path_exists",
            symbol: "lpp_path_exists",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_path_exists",
            symbol: "lpp_path_exists",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "path_join",
            symbol: "lpp_path_join",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_path_join",
            symbol: "lpp_path_join",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // ── Binary buffer library (runtime/lpp_buf.c) ──────────────────────
        Builtin {
            name: "str_len",
            symbol: "lpp_str_len",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64x2",
            symbol: "lpp_vec_i64x2",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::VectorI64x2,
            cl_params: &[0, 0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64x2_splat",
            symbol: "lpp_vec_i64x2_splat",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::VectorI64x2,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64x2_add",
            symbol: "lpp_vec_i64x2_add",
            params: &[ParamType::Specific(TypeRef::VectorI64x2), ParamType::Specific(TypeRef::VectorI64x2)],
            return_type: TypeRef::VectorI64x2,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64x2_sub",
            symbol: "lpp_vec_i64x2_sub",
            params: &[ParamType::Specific(TypeRef::VectorI64x2), ParamType::Specific(TypeRef::VectorI64x2)],
            return_type: TypeRef::VectorI64x2,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64x2_mul",
            symbol: "lpp_vec_i64x2_mul",
            params: &[ParamType::Specific(TypeRef::VectorI64x2), ParamType::Specific(TypeRef::VectorI64x2)],
            return_type: TypeRef::VectorI64x2,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64x2_xor",
            symbol: "lpp_vec_i64x2_xor",
            params: &[ParamType::Specific(TypeRef::VectorI64x2), ParamType::Specific(TypeRef::VectorI64x2)],
            return_type: TypeRef::VectorI64x2,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64x2_shr",
            symbol: "lpp_vec_i64x2_shr",
            params: &[ParamType::Specific(TypeRef::VectorI64x2), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::VectorI64x2,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64x2_shr_var",
            symbol: "lpp_vec_i64x2_shr_var",
            params: &[ParamType::Specific(TypeRef::VectorI64x2), ParamType::Specific(TypeRef::VectorI64x2)],
            return_type: TypeRef::VectorI64x2,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64x2_extract",
            symbol: "lpp_vec_i64x2_extract",
            params: &[ParamType::Specific(TypeRef::VectorI64x2), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64x2_sum",
            symbol: "lpp_vec_i64x2_sum",
            params: &[ParamType::Specific(TypeRef::VectorI64x2)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "vec_i64_checksum",
            symbol: "lpp_vec_i64_checksum",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_vec_i64_checksum",
            symbol: "lpp_vec_i64_checksum",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_len",
            symbol: "lpp_str_len",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "buf_alloc",
            symbol: "lpp_buf_alloc",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_buf_alloc",
            symbol: "lpp_buf_alloc",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "buf_free",
            symbol: "lpp_buf_free",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_buf_free",
            symbol: "lpp_buf_free",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "buf_len",
            symbol: "lpp_buf_len",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_buf_len",
            symbol: "lpp_buf_len",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "buf_get8",
            symbol: "lpp_buf_get8",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_buf_get8",
            symbol: "lpp_buf_get8",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "buf_set8",
            symbol: "lpp_buf_set8",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_buf_set8",
            symbol: "lpp_buf_set8",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "buf_set32le",
            symbol: "lpp_buf_set32le",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_buf_set32le",
            symbol: "lpp_buf_set32le",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "buf_get32le",
            symbol: "lpp_buf_get32le",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_buf_get32le",
            symbol: "lpp_buf_get32le",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "buf_set16le",
            symbol: "lpp_buf_set16le",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_buf_set16le",
            symbol: "lpp_buf_set16le",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "buf_get16le",
            symbol: "lpp_buf_get16le",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_buf_get16le",
            symbol: "lpp_buf_get16le",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "buf_read",
            symbol: "lpp_buf_read",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_buf_read",
            symbol: "lpp_buf_read",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "buf_write",
            symbol: "lpp_buf_write",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_buf_write",
            symbol: "lpp_buf_write",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "buf_crc32",
            symbol: "lpp_buf_crc32",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_buf_crc32",
            symbol: "lpp_buf_crc32",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "buf_copy",
            symbol: "lpp_buf_copy",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_buf_copy",
            symbol: "lpp_buf_copy",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "buf_write_str",
            symbol: "lpp_buf_write_str",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_buf_write_str",
            symbol: "lpp_buf_write_str",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "buf_read_str",
            symbol: "lpp_buf_read_str",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_buf_read_str",
            symbol: "lpp_buf_read_str",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        // ── String character operations ──────────────────────────────
        Builtin {
            name: "char_at",
            symbol: "lpp_char_at",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_char_at",
            symbol: "lpp_char_at",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "ord",
            symbol: "lpp_ord",
            params: &[
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_ord",
            symbol: "lpp_ord",
            params: &[
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "chr",
            symbol: "lpp_chr",
            params: &[
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_chr",
            symbol: "lpp_chr",
            params: &[
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_find",
            symbol: "lpp_str_find",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_find",
            symbol: "lpp_str_find",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_contains",
            symbol: "lpp_str_contains",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_contains",
            symbol: "lpp_str_contains",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_starts_with",
            symbol: "lpp_str_starts_with",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_starts_with",
            symbol: "lpp_str_starts_with",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_ends_with",
            symbol: "lpp_str_ends_with",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_ends_with",
            symbol: "lpp_str_ends_with",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_upper",
            symbol: "lpp_str_upper",
            params: &[
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_upper",
            symbol: "lpp_str_upper",
            params: &[
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_lower",
            symbol: "lpp_str_lower",
            params: &[
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_lower",
            symbol: "lpp_str_lower",
            params: &[
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_trim",
            symbol: "lpp_str_trim",
            params: &[
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_trim",
            symbol: "lpp_str_trim",
            params: &[
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_replace",
            symbol: "lpp_str_replace",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_replace",
            symbol: "lpp_str_replace",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "int_to_str",
            symbol: "lpp_int_to_str",
            params: &[
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_int_to_str",
            symbol: "lpp_int_to_str",
            params: &[
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "float_to_str",
            symbol: "lpp_float_to_str",
            params: &[
                ParamType::Specific(TypeRef::Float),
            ],
            return_type: TypeRef::Str,
            cl_params: &[3],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_float_to_str",
            symbol: "lpp_float_to_str",
            params: &[
                ParamType::Specific(TypeRef::Float),
            ],
            return_type: TypeRef::Str,
            cl_params: &[3],
            cl_return: Some(0),
        },
        Builtin {
            name: "bool_to_str",
            symbol: "lpp_bool_to_str",
            params: &[
                ParamType::Specific(TypeRef::Bool),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_bool_to_str",
            symbol: "lpp_bool_to_str",
            params: &[
                ParamType::Specific(TypeRef::Bool),
            ],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // ── Native GUI & Windowing ──────────────────────────────────────────
        Builtin {
            name: "gui_window_create",
            symbol: "lpp_gui_window_create",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_window_is_open",
            symbol: "lpp_gui_window_is_open",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_window_width",
            symbol: "lpp_gui_window_width",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_window_height",
            symbol: "lpp_gui_window_height",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_window_poll_events",
            symbol: "lpp_gui_window_poll_events",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_clear",
            symbol: "lpp_gui_clear",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "gui_draw_rect",
            symbol: "lpp_gui_draw_rect",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0, 0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "gui_draw_rounded_rect",
            symbol: "lpp_gui_draw_rounded_rect",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0, 0, 0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "gui_mouse_x",
            symbol: "lpp_gui_mouse_x",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_mouse_y",
            symbol: "lpp_gui_mouse_y",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_mouse_down",
            symbol: "lpp_gui_mouse_down",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_key_down",
            symbol: "lpp_gui_key_down",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_draw_text",
            symbol: "lpp_gui_draw_text",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "gui_present",
            symbol: "lpp_gui_present",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "gui_window_close",
            symbol: "lpp_gui_window_close",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "gui_draw_circle",
            symbol: "lpp_gui_draw_circle",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "gui_draw_line",
            symbol: "lpp_gui_draw_line",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Int),
            ],
            return_type: TypeRef::Void,
            cl_params: &[0, 0, 0, 0, 0, 0, 0],
            cl_return: None,
        },
        Builtin {
            name: "gui_measure_text_width",
            symbol: "lpp_gui_measure_text_width",
            params: &[
                ParamType::Specific(TypeRef::Int),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_dialog_message",
            symbol: "lpp_gui_dialog_message",
            params: &[
                ParamType::Specific(TypeRef::Str),
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "gui_get_ticks_ms",
            symbol: "lpp_gui_get_ticks_ms",
            params: &[],
            return_type: TypeRef::Int,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "str_to_int",
            symbol: "lpp_str_to_int",
            params: &[
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_str_to_int",
            symbol: "lpp_str_to_int",
            params: &[
                ParamType::Specific(TypeRef::Str),
            ],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin { name: "lpp_abs", symbol: "lpp_abs", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_min", symbol: "lpp_min", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_max", symbol: "lpp_max", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "sqrt", symbol: "lpp_sqrt", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3], cl_return: Some(3) },
        Builtin { name: "lpp_sqrt", symbol: "lpp_sqrt", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3], cl_return: Some(3) },
        Builtin { name: "sin", symbol: "lpp_sin", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3], cl_return: Some(3) },
        Builtin { name: "lpp_sin", symbol: "lpp_sin", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3], cl_return: Some(3) },
        Builtin { name: "cos", symbol: "lpp_cos", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3], cl_return: Some(3) },
        Builtin { name: "lpp_cos", symbol: "lpp_cos", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3], cl_return: Some(3) },
        Builtin { name: "tan", symbol: "lpp_tan", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3], cl_return: Some(3) },
        Builtin { name: "lpp_tan", symbol: "lpp_tan", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3], cl_return: Some(3) },
        Builtin { name: "lpp_floor", symbol: "lpp_floor", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3], cl_return: Some(3) },
        Builtin { name: "lpp_ceil", symbol: "lpp_ceil", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3], cl_return: Some(3) },
        Builtin { name: "lpp_pow", symbol: "lpp_pow", params: &[ParamType::Specific(TypeRef::Float), ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Float, cl_params: &[3, 3], cl_return: Some(3) },
        Builtin { name: "int_pow", symbol: "lpp_int_pow", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_int_pow", symbol: "lpp_int_pow", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "int_to_float", symbol: "lpp_int_to_float", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Float, cl_params: &[0], cl_return: Some(3) },
        Builtin { name: "lpp_int_to_float", symbol: "lpp_int_to_float", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Float, cl_params: &[0], cl_return: Some(3) },
        Builtin { name: "float_to_int", symbol: "lpp_float_to_int", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Int, cl_params: &[3], cl_return: Some(0) },
        Builtin { name: "lpp_float_to_int", symbol: "lpp_float_to_int", params: &[ParamType::Specific(TypeRef::Float)], return_type: TypeRef::Int, cl_params: &[3], cl_return: Some(0) },
        Builtin { name: "random", symbol: "lpp_random", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "lpp_random", symbol: "lpp_random", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "random_range", symbol: "lpp_random_range", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_random_range", symbol: "lpp_random_range", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "random_seed", symbol: "lpp_random_seed", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0], cl_return: None },
        Builtin { name: "lpp_random_seed", symbol: "lpp_random_seed", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0], cl_return: None },
        Builtin { name: "time_ms", symbol: "lpp_time_ms", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "lpp_time_ms", symbol: "lpp_time_ms", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "sys_mem_total", symbol: "lpp_sys_mem_total", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "lpp_sys_mem_total", symbol: "lpp_sys_mem_total", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "sys_mem_free", symbol: "lpp_sys_mem_free", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "lpp_sys_mem_free", symbol: "lpp_sys_mem_free", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "sys_cpu_usage", symbol: "lpp_sys_cpu_usage", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "lpp_sys_cpu_usage", symbol: "lpp_sys_cpu_usage", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "sys_uptime", symbol: "lpp_sys_uptime", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "lpp_sys_uptime", symbol: "lpp_sys_uptime", params: &[], return_type: TypeRef::Int, cl_params: &[], cl_return: Some(0) },
        Builtin { name: "sleep_ms", symbol: "lpp_sleep_ms", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0], cl_return: None },
        Builtin { name: "lpp_sleep_ms", symbol: "lpp_sleep_ms", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0], cl_return: None },
        Builtin { name: "exit", symbol: "lpp_exit", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0], cl_return: None },
        Builtin { name: "lpp_exit", symbol: "lpp_exit", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0], cl_return: None },
        Builtin { name: "lpp_str_eq", symbol: "lpp_str_eq", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "map_put_str", symbol: "lpp_map_put_str", params: &[ParamType::Any, ParamType::Specific(TypeRef::Str), ParamType::Any], return_type: TypeRef::Void, cl_params: &[0, 0, 0], cl_return: None },
        Builtin { name: "map_get_str", symbol: "lpp_map_get_str", params: &[ParamType::Any, ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "map_has_str", symbol: "lpp_map_has_str", params: &[ParamType::Any, ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "map_remove_str", symbol: "lpp_map_remove_str", params: &[ParamType::Any, ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Void, cl_params: &[0, 0], cl_return: None },
        Builtin { name: "lpp_c_malloc", symbol: "lpp_c_malloc", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_c_free", symbol: "lpp_c_free", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0], cl_return: None },
        Builtin { name: "lpp_c_load_u8", symbol: "lpp_c_load_u8", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_c_store_u8", symbol: "lpp_c_store_u8", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0, 0, 0], cl_return: None },
        Builtin { name: "lpp_c_load_i32", symbol: "lpp_c_load_i32", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_c_store_i32", symbol: "lpp_c_store_i32", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0, 0, 0], cl_return: None },
        Builtin { name: "lpp_c_load_i64", symbol: "lpp_c_load_i64", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_c_store_i64", symbol: "lpp_c_store_i64", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0, 0, 0], cl_return: None },
        Builtin { name: "dlopen", symbol: "dlopen", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "dlsym", symbol: "dlsym", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "dlclose", symbol: "dlclose", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "dlerror", symbol: "dlerror", params: &[], return_type: TypeRef::Str, cl_params: &[], cl_return: Some(0) },
    ];
    BUILTINS
}
