use crate::typecheck::TypeRef;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ParamType {
    Specific(TypeRef),
    Any,
}

#[derive(Debug, Clone)]
pub struct Builtin {
    pub name: &'static str,
    pub symbol: &'static str,
    pub params: &'static [ParamType],
    pub return_type: TypeRef,
    // Cranelift parameter type tags: 0 = I64, 1 = I8, 2 = I32, 3 = F64
    pub cl_params: &'static [u8],
    pub cl_return: Option<u8>,
}

pub fn get_builtins() -> &'static [Builtin] {
    static BUILTINS: &[Builtin] = &[
        // Overloaded/generic frontend functions
        Builtin {
            name: "print",
            symbol: "",
            params: &[ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: None,
        },
        // Linkable runtime targets
        Builtin {
            name: "print_str",
            symbol: "lpp_print_str",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_print_str",
            symbol: "lpp_print_str",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_print_int",
            symbol: "lpp_print_int",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_print_float",
            symbol: "lpp_print_float",
            params: &[ParamType::Specific(TypeRef::Float)],
            return_type: TypeRef::Void,
            cl_params: &[3],
            cl_return: None,
        },
        Builtin {
            name: "input",
            symbol: "lpp_input",
            params: &[],
            return_type: TypeRef::Str,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_input",
            symbol: "lpp_input",
            params: &[],
            return_type: TypeRef::Str,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_free_str",
            symbol: "lpp_free_str",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_arc_retain",
            symbol: "lpp_arc_retain",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_arc_release",
            symbol: "lpp_arc_release",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // ARC-managed allocation used by AOT struct lowering. The pointer is
        // represented as I64 in the current 64-bit L++ runtime ABI.
        Builtin {
            name: "lpp_arc_alloc",
            symbol: "lpp_arc_alloc",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // AOT-only typed ARC allocation: size plus a generated destructor
        // function pointer, both represented as I64 in the current ABI.
        Builtin {
            name: "lpp_arc_alloc_with_destructor",
            symbol: "lpp_arc_alloc_with_destructor",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_closure_destroy",
            symbol: "lpp_closure_destroy",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_alloc",
            symbol: "lpp_alloc",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_free",
            symbol: "lpp_free",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_thread_spawn",
            symbol: "lpp_thread_spawn",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        // Alias: `len` and `get` for ergonomic list access
        Builtin { name: "len", symbol: "lpp_list_len", params: &[ParamType::Any], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "get", symbol: "lpp_list_get", params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin {
            name: "list_new",
            symbol: "lpp_list_new",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_new",
            symbol: "lpp_list_new",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_new_arc",
            symbol: "lpp_list_new_arc",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "list_push",
            symbol: "lpp_list_push",
            // TypeChecker derives the element type from the concrete List[T].
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_push",
            symbol: "lpp_list_push",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_push_arc",
            symbol: "lpp_list_push_arc",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "list_get",
            symbol: "lpp_list_get",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_get",
            symbol: "lpp_list_get",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_get_arc",
            symbol: "lpp_list_get_arc",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "list_len",
            symbol: "lpp_list_len",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_len",
            symbol: "lpp_list_len",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "list_free",
            symbol: "lpp_list_free",
            params: &[ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_free",
            symbol: "lpp_list_free",
            params: &[ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // Networking — Full Go-style API
        // Dial (TCP + DNS + deadline)
        Builtin { name: "net_dial", symbol: "lpp_net_dial", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_dial", symbol: "lpp_net_dial", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0, 0], cl_return: Some(0) },
        // Dial UDP
        Builtin { name: "net_dial_udp", symbol: "lpp_net_dial_udp", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_dial_udp", symbol: "lpp_net_dial_udp", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0, 0], cl_return: Some(0) },
        // Listen TCP
        Builtin { name: "net_listen", symbol: "lpp_net_listen", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_net_listen", symbol: "lpp_net_listen", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        // Listen UDP
        Builtin { name: "net_listen_udp", symbol: "lpp_net_listen_udp", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_net_listen_udp", symbol: "lpp_net_listen_udp", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        // Accept (with timeout)
        Builtin { name: "net_accept", symbol: "lpp_net_accept", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_net_accept", symbol: "lpp_net_accept", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "net_accept_timeout", symbol: "lpp_net_accept_timeout", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_accept_timeout", symbol: "lpp_net_accept_timeout", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        // Send
        Builtin { name: "net_send", symbol: "lpp_net_send", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_send", symbol: "lpp_net_send", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        // Send all
        Builtin { name: "net_send_all", symbol: "lpp_net_send_all", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_send_all", symbol: "lpp_net_send_all", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        // Recv
        Builtin { name: "net_recv", symbol: "lpp_net_recv", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Str, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_recv", symbol: "lpp_net_recv", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Str, cl_params: &[0, 0], cl_return: Some(0) },
        // Recv UDP
        Builtin { name: "net_recv_udp", symbol: "lpp_net_recv_udp", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Str, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_recv_udp", symbol: "lpp_net_recv_udp", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Str, cl_params: &[0, 0], cl_return: Some(0) },
        // Close
        Builtin { name: "net_close", symbol: "lpp_net_close", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0], cl_return: None },
        Builtin { name: "lpp_net_close", symbol: "lpp_net_close", params: &[ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0], cl_return: None },
        // Deadlines
        Builtin { name: "net_set_deadline", symbol: "lpp_net_set_deadline", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_set_deadline", symbol: "lpp_net_set_deadline", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0, 0], cl_return: Some(0) },
        Builtin { name: "net_set_timeout", symbol: "lpp_net_set_timeout", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_set_timeout", symbol: "lpp_net_set_timeout", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        // Keepalive
        Builtin { name: "net_set_keepalive", symbol: "lpp_net_set_keepalive", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0, 0, 0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_set_keepalive", symbol: "lpp_net_set_keepalive", params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0, 0, 0, 0], cl_return: Some(0) },
        // DNS
        Builtin { name: "net_resolve", symbol: "lpp_net_resolve", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_net_resolve", symbol: "lpp_net_resolve", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0], cl_return: Some(0) },
        // HTTP
        Builtin { name: "http_get", symbol: "lpp_http_get", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Str, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_http_get", symbol: "lpp_http_get", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Str, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "http_post", symbol: "lpp_http_post", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Str, cl_params: &[0, 0, 0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_http_post", symbol: "lpp_http_post", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Str, cl_params: &[0, 0, 0, 0], cl_return: Some(0) },
        // Legacy compat
        Builtin { name: "net_connect", symbol: "lpp_net_connect", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_net_connect", symbol: "lpp_net_connect", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        // JSON parsing
        Builtin {
            name: "json_parse",
            symbol: "lpp_json_parse",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_parse",
            symbol: "lpp_json_parse",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_get_int",
            symbol: "lpp_json_get_int",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_get_int",
            symbol: "lpp_json_get_int",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_get_str",
            symbol: "lpp_json_get_str",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_get_str",
            symbol: "lpp_json_get_str",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_get_obj",
            symbol: "lpp_json_get_obj",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_get_obj",
            symbol: "lpp_json_get_obj",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_free",
            symbol: "lpp_json_free",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_json_free",
            symbol: "lpp_json_free",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // Utilities
        Builtin {
            name: "parse_int",
            symbol: "lpp_parse_int",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_parse_int",
            symbol: "lpp_parse_int",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // File I/O (Existing & New)
        Builtin {
            name: "read_file",
            symbol: "lpp_read_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_read_file",
            symbol: "lpp_read_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "write_file",
            symbol: "lpp_write_file",
            params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_write_file",
            symbol: "lpp_write_file",
            params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "append_file",
            symbol: "lpp_append_file",
            params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_append_file",
            symbol: "lpp_append_file",
            params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "delete_file",
            symbol: "lpp_delete_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_delete_file",
            symbol: "lpp_delete_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "file_exists",
            symbol: "lpp_file_exists",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Bool,
            cl_params: &[0],
            cl_return: Some(1), // I8 tag for bool
        },
        Builtin {
            name: "lpp_file_exists",
            symbol: "lpp_file_exists",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Bool,
            cl_params: &[0],
            cl_return: Some(1),
        },
        Builtin { name: "file_size", symbol: "lpp_file_size", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_file_size", symbol: "lpp_file_size", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "file_copy", symbol: "lpp_file_copy", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_file_copy", symbol: "lpp_file_copy", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "file_move", symbol: "lpp_file_move", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_file_move", symbol: "lpp_file_move", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        // ── String library (runtime/lpp_str.c) ──────────────────────────────
        Builtin { name: "str_concat", symbol: "lpp_str_concat", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_str_concat", symbol: "lpp_str_concat", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "str_split", symbol: "lpp_str_split", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_str_split", symbol: "lpp_str_split", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Void, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "str_find", symbol: "lpp_str_find", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_str_find", symbol: "lpp_str_find", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "str_replace", symbol: "lpp_str_replace", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0, 0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_str_replace", symbol: "lpp_str_replace", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0, 0, 0], cl_return: Some(0) },
        Builtin { name: "str_substr", symbol: "lpp_str_substr", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Str, cl_params: &[0, 0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_str_substr", symbol: "lpp_str_substr", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)], return_type: TypeRef::Str, cl_params: &[0, 0, 0], cl_return: Some(0) },
        Builtin { name: "str_trim", symbol: "lpp_str_trim", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_str_trim", symbol: "lpp_str_trim", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0], cl_return: Some(0) },
        // ── Process execution (runtime/lpp_exec.c) ──────────────────────────
        Builtin { name: "command_exec", symbol: "lpp_command_exec", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_command_exec", symbol: "lpp_command_exec", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "command_output", symbol: "lpp_command_output", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_command_output", symbol: "lpp_command_output", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "env_get", symbol: "lpp_env_get", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_env_get", symbol: "lpp_env_get", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "env_set", symbol: "lpp_env_set", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_env_set", symbol: "lpp_env_set", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        // ── Directory / filesystem (runtime/lpp_dir.c) ──────────────────────
        Builtin { name: "dir_create", symbol: "lpp_dir_create", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_dir_create", symbol: "lpp_dir_create", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "dir_list", symbol: "lpp_dir_list", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Void, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_dir_list", symbol: "lpp_dir_list", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Void, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "dir_remove", symbol: "lpp_dir_remove", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_dir_remove", symbol: "lpp_dir_remove", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "path_exists", symbol: "lpp_path_exists", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_path_exists", symbol: "lpp_path_exists", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "path_join", symbol: "lpp_path_join", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_path_join", symbol: "lpp_path_join", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Str, cl_params: &[0, 0], cl_return: Some(0) },
    ];
    BUILTINS
}
