use crate::typecheck::TypeRef;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ParamType {
    Specific(TypeRef),
    Any,
}

#[derive(Debug, Clone)]
pub struct Builtin {
    pub name: &'static str,
    pub symbol: &'static str,
    pub params: &'static [ParamType],
    pub return_type: TypeRef,
    // Cranelift parameter type tags: 0 = I64, 1 = I8, 2 = I32, 3 = F64
    pub cl_params: &'static [u8],
    pub cl_return: Option<u8>,
}

pub fn get_builtins() -> &'static [Builtin] {
    static BUILTINS: &[Builtin] = &[
        // Overloaded/generic frontend functions
        Builtin {
            name: "print",
            symbol: "",
            params: &[ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: None,
        },
        // Linkable runtime targets
        Builtin {
            name: "print_str",
            symbol: "lpp_print_str",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_print_str",
            symbol: "lpp_print_str",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_print_int",
            symbol: "lpp_print_int",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_print_float",
            symbol: "lpp_print_float",
            params: &[ParamType::Specific(TypeRef::Float)],
            return_type: TypeRef::Void,
            cl_params: &[3],
            cl_return: None,
        },
        Builtin {
            name: "input",
            symbol: "lpp_input",
            params: &[],
            return_type: TypeRef::Str,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_input",
            symbol: "lpp_input",
            params: &[],
            return_type: TypeRef::Str,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_free_str",
            symbol: "lpp_free_str",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_arc_retain",
            symbol: "lpp_arc_retain",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_arc_release",
            symbol: "lpp_arc_release",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // ARC-managed allocation used by AOT struct lowering. The pointer is
        // represented as I64 in the current 64-bit L++ runtime ABI.
        Builtin {
            name: "lpp_arc_alloc",
            symbol: "lpp_arc_alloc",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // AOT-only typed ARC allocation: size plus a generated destructor
        // function pointer, both represented as I64 in the current ABI.
        Builtin {
            name: "lpp_arc_alloc_with_destructor",
            symbol: "lpp_arc_alloc_with_destructor",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_closure_destroy",
            symbol: "lpp_closure_destroy",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_alloc",
            symbol: "lpp_alloc",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_free",
            symbol: "lpp_free",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_thread_spawn",
            symbol: "lpp_thread_spawn",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        // Lists
        Builtin {
            name: "list_new",
            symbol: "lpp_list_new",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_new",
            symbol: "lpp_list_new",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_new_arc",
            symbol: "lpp_list_new_arc",
            params: &[],
            return_type: TypeRef::Void,
            cl_params: &[],
            cl_return: Some(0),
        },
        Builtin {
            name: "list_push",
            symbol: "lpp_list_push",
            // TypeChecker derives the element type from the concrete List[T].
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_push",
            symbol: "lpp_list_push",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_push_arc",
            symbol: "lpp_list_push_arc",
            params: &[ParamType::Any, ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0, 0],
            cl_return: None,
        },
        Builtin {
            name: "list_get",
            symbol: "lpp_list_get",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_get",
            symbol: "lpp_list_get",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_get_arc",
            symbol: "lpp_list_get_arc",
            params: &[ParamType::Any, ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "list_len",
            symbol: "lpp_list_len",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_list_len",
            symbol: "lpp_list_len",
            params: &[ParamType::Any],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "list_free",
            symbol: "lpp_list_free",
            params: &[ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_list_free",
            symbol: "lpp_list_free",
            params: &[ParamType::Any],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // Networking
        Builtin {
            name: "net_connect",
            symbol: "lpp_net_connect",
            params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_connect",
            symbol: "lpp_net_connect",
            params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "net_listen",
            symbol: "lpp_net_listen",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_listen",
            symbol: "lpp_net_listen",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "net_accept",
            symbol: "lpp_net_accept",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_accept",
            symbol: "lpp_net_accept",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "net_send",
            symbol: "lpp_net_send",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_send",
            symbol: "lpp_net_send",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // Writes the entire UTF-8 payload or returns -1. This is the safe
        // default for request/response protocols: a single OS send may write
        // only a prefix of a buffer.
        Builtin {
            name: "net_send_all",
            symbol: "lpp_net_send_all",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_send_all",
            symbol: "lpp_net_send_all",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        // Applies both receive and send deadlines. Returns 1 on success and 0
        // on invalid handles, unsupported platform configuration, or failure.
        Builtin {
            name: "net_set_timeout",
            symbol: "lpp_net_set_timeout",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_set_timeout",
            symbol: "lpp_net_set_timeout",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "net_recv",
            symbol: "lpp_net_recv",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_net_recv",
            symbol: "lpp_net_recv",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "net_close",
            symbol: "lpp_net_close",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_net_close",
            symbol: "lpp_net_close",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // JSON parsing
        Builtin {
            name: "json_parse",
            symbol: "lpp_json_parse",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_parse",
            symbol: "lpp_json_parse",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_get_int",
            symbol: "lpp_json_get_int",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_get_int",
            symbol: "lpp_json_get_int",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_get_str",
            symbol: "lpp_json_get_str",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_get_str",
            symbol: "lpp_json_get_str",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_get_obj",
            symbol: "lpp_json_get_obj",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_json_get_obj",
            symbol: "lpp_json_get_obj",
            params: &[ParamType::Specific(TypeRef::Int), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "json_free",
            symbol: "lpp_json_free",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        Builtin {
            name: "lpp_json_free",
            symbol: "lpp_json_free",
            params: &[ParamType::Specific(TypeRef::Int)],
            return_type: TypeRef::Void,
            cl_params: &[0],
            cl_return: None,
        },
        // Utilities
        Builtin {
            name: "parse_int",
            symbol: "lpp_parse_int",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_parse_int",
            symbol: "lpp_parse_int",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        // File I/O (Existing & New)
        Builtin {
            name: "read_file",
            symbol: "lpp_read_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_read_file",
            symbol: "lpp_read_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Str,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "write_file",
            symbol: "lpp_write_file",
            params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_write_file",
            symbol: "lpp_write_file",
            params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "append_file",
            symbol: "lpp_append_file",
            params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_append_file",
            symbol: "lpp_append_file",
            params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0, 0],
            cl_return: Some(0),
        },
        Builtin {
            name: "delete_file",
            symbol: "lpp_delete_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "lpp_delete_file",
            symbol: "lpp_delete_file",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Int,
            cl_params: &[0],
            cl_return: Some(0),
        },
        Builtin {
            name: "file_exists",
            symbol: "lpp_file_exists",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Bool,
            cl_params: &[0],
            cl_return: Some(1), // I8 tag for bool
        },
        Builtin {
            name: "lpp_file_exists",
            symbol: "lpp_file_exists",
            params: &[ParamType::Specific(TypeRef::Str)],
            return_type: TypeRef::Bool,
            cl_params: &[0],
            cl_return: Some(1),
        },
        Builtin { name: "file_size", symbol: "lpp_file_size", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "lpp_file_size", symbol: "lpp_file_size", params: &[ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0], cl_return: Some(0) },
        Builtin { name: "file_copy", symbol: "lpp_file_copy", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_file_copy", symbol: "lpp_file_copy", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "file_move", symbol: "lpp_file_move", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
        Builtin { name: "lpp_file_move", symbol: "lpp_file_move", params: &[ParamType::Specific(TypeRef::Str), ParamType::Specific(TypeRef::Str)], return_type: TypeRef::Int, cl_params: &[0, 0], cl_return: Some(0) },
    ];
    BUILTINS
}
