#!/usr/bin/env python3
"""Generate a single-file 10k+ line L++ list/ARC/game stress workload.

The generated source is intentionally ignored by Git: it is a reproducible test
artifact, not hand-maintained language source. It targets current List[Int]
AOT support plus parser/typechecker/codegen scale.
"""
from pathlib import Path

OUT = Path(__file__).with_name("generated") / "list_game_stress_10k.lpp"
LEVELS = 1_670

lines = [
    "# L++ List Labyrinth — generated 10k+ line stress game.",
    "# Generated by safety/generate_list_game_stress.py; do not edit by hand.",
    "# Exercises List[Int], list allocation/growth/get/len, arithmetic, branches,",
    "# loops, function call graph breadth, file output, and AOT compilation scale.",
    "",
    "struct Player:",
    "    hp: Int",
    "    score: Int",
    "",
    "def clamp(value: Int, low: Int, high: Int) -> Int:",
    "    if value < low:",
    "        return low",
    "    else:",
    "        if value > high:",
    "            return high",
    "        else:",
    "            return value",
    "",
    "def game_turn(seed: Int) -> Int:",
    "    inventory := [1, 2, 3, 5, 8, 13]",
    "    list_push(inventory, seed)",
    "    energy := list_get(inventory, 0) + list_get(inventory, 1)",
    "    step := 0",
    "    while step < 4:",
    "        energy = energy + list_get(inventory, step)",
    "        step = step + 1",
    "    return clamp(energy + list_len(inventory), 0, 1000000)",
    "",
]
for n in range(LEVELS):
    k = n % 97 + 1
    lines += [
        f"def labyrinth_room_{n:04d}(seed: Int) -> Int:",
        f"    tiles := [{k}, {k+1}, {k+2}, {k+3}]",
        f"    loot := [{n % 11}, {n % 13}, {n % 17}]",
        "    list_push(tiles, seed)",
        f"    list_push(loot, seed + {n % 29})",
        "    door := list_get(tiles, 0) + list_get(loot, 1)",
        "    if door % 2 == 0:",
        "        return door + list_len(tiles) + list_len(loot)",
        "    else:",
        "        return door - list_len(tiles) + list_len(loot)",
        "",
    ]
lines += [
    "def main():",
    "    player := Player()",
    "    player.hp = 100",
    "    player.score = 0",
    "    map := [3, 1, 4, 1, 5, 9, 2, 6]",
    "    round := 0",
    "    while round < 12:",
    "        list_push(map, round)",
    "        player.score = player.score + game_turn(round)",
    "        if round % 3 == 0:",
    "            player.score = player.score + labyrinth_room_0000(round)",
    "        else:",
    "            player.score = player.score + labyrinth_room_1669(round)",
    "        round = round + 1",
    "    # Persistent game save path: tests file runtime integration in host-link mode.",
    "    write_file(\"lpp_list_labyrinth_save.txt\", \"L++ List Labyrinth completed\")",
    "    print(player.score + list_len(map))",
]
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {OUT}: {len(lines)} lines, {LEVELS} generated rooms")
if len(lines) < 10_000:
    raise SystemExit("generator regression: expected at least 10,000 lines")
