[package]
name = "lpp-codegen-llvm"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
lpp-codegen-api = { path = "../lpp-codegen-api" }
lpp-config = { path = "../lpp-config" }
lpp-mir = { path = "../lpp-mir" }
lpp-runtime-abi = { path = "../lpp-runtime-abi" }
lpp-types = { path = "../lpp-types" }

[dev-dependencies]
lpp-hir = { path = "../lpp-hir" }
lpp-ownership = { path = "../lpp-ownership" }
