```yaml
name: Mac Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  mac-build:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build L++ toolchain on macOS
        run: |
          cargo build --release --bin lpp --bin lpp-link
```
